#######################################
#                Tasks                #
#######################################
tasks:
  - name: build
    tags: ["dist"]
    commands:
      - command: git.get_project
        type: system
        params:
          directory: gopath/src/github.com/mongodb/redalert

      - command: shell.exec
        params:
          shell: bash
          script: |
            set -o errexit
            set -o verbose

            export GOPATH=`pwd`/gopath

            virtualenv --python python3 venv3
            source venv3/bin/activate
            cd gopath/src/github.com/mongodb/redalert
            pip install -r ./requirements.txt

            ${build_env|} go test ./...
            ${build_env|} go build
            tar -cvzf  ./redalert.tgz ./redalert

      - command: s3.put
        type: system
        params:
          aws_key: ${aws_key}
          aws_secret: ${aws_secret}
          local_file: gopath/src/github.com/mongodb/redalert/redalert.tgz
          remote_file: redalert/${build_id}-${build_variant}/redalert-dist-${revision}.tgz
          bucket: evg-project-redalert
          content_type: application/x-gzip
          permissions: public-read
          display_name: dist.tar.tgz


#######################################
#           Buildvariants             #
#######################################
buildvariants:
  - name: ubuntu2004
    display_name: Ubuntu 20.04
    run_on:
      - ubuntu2004-small
    expansions:
      build_env: "PATH=/opt/golang/go1.18/bin:$PATH GOROOT=/opt/golang/go1.18"
    tasks:
      - ".dist"
  
  - name: ubuntu2004-arm64
    display_name: Ubuntu 20.04 ARM64
    run_on:
      - ubuntu2004-arm64-small
    expansions:
      build_env: "PATH=/opt/golang/go1.18/bin:$PATH GOROOT=/opt/golang/go1.18"
    tasks:
      - ".dist"